ANTIBODY_HOME="$(antibody home)"

export ZSH="$ANTIBODY_HOME"/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh

source ~/.zsh_plugins.sh

source ~/.dotfiles/zsh/functions/functions.zsh

source ~/.dotfiles/zsh/env.zsh

source ~/.local/bin/virtualenvwrapper.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/julian/mambaforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/julian/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/home/julian/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/home/julian/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

