# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Clone antidote if necessary.
[[ -d ~/.dotfiles/.antidote ]] ||
  git clone https://github.com/mattmc3/antidote ~/.dotfiles/.antidote

source ~/.dotfiles/.antidote/antidote.zsh
antidote load ~/.dotfiles/zsh/plugins.txt

source ~/.dotfiles/zsh/plugins.zsh

source ~/.dotfiles/zsh/functions/functions.zsh

source ~/.dotfiles/zsh/env.zsh

# source ~/.local/bin/virtualenvwrapper.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/julian/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/julian/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/home/julian/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/home/julian/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/julian/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/home/julian/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
